name: Pull Request
description: Submit changes to Unity Helpers
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What does this PR do?
    validations:
      required: true

  - type: input
    id: related-issue
    attributes:
      label: Related Issue
      description: "Link to related issue (e.g., #123)"
      placeholder: "#123"

  - type: dropdown
    id: change-type
    attributes:
      label: Type of Change
      options:
        - Bug fix (non-breaking)
        - New feature (non-breaking)
        - Breaking change
        - Documentation update
        - Performance improvement
        - Code refactoring
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have read the contributing guidelines
          required: true
        - label: My code follows the project style guidelines
          required: true
        - label: I have added tests covering my changes
        - label: I have updated relevant documentation
        - label: All new and existing tests pass
