version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: weekly

updates:
  # GitHub Actions, NuGet, and npm updates are grouped into one large PR.
  - package-ecosystem: github-actions
    directory: /
    assignees:
      - wallstop
    reviewers:
      - wallstop
    patterns:
      - "*"
    multi-ecosystem-group: all-dependencies

  - package-ecosystem: nuget
    directory: /
    assignees:
      - wallstop
    reviewers:
      - wallstop
    patterns:
      - "*"
    multi-ecosystem-group: all-dependencies

  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase
    assignees:
      - wallstop
    reviewers:
      - wallstop
    patterns:
      - "*"
    multi-ecosystem-group: all-dependencies
