namespace WallstopStudios.UnityHelpers.Editor.Utils
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Text;
    using Core.Attributes;
    using UnityEditor;
    using UnityEditor.Compilation;
    using UnityEditor.PackageManager;
    using UnityEngine;

    [InitializeOnLoad]
    internal static class SingletonAutoLoadManifestGenerator
    {
        private const string OutputRelativePath =
            "Runtime/Generated/SingletonAutoLoadManifest.g.cs";
        private const string AutoGeneratedHeader =
            "// <auto-generated> Singleton auto-load manifest. Do not edit manually.";

        static SingletonAutoLoadManifestGenerator()
        {
            AssemblyReloadEvents.afterAssemblyReload += GenerateDeferred;
            GenerateDeferred();
        }

        private static void GenerateDeferred()
        {
            EditorApplication.delayCall += Generate;
        }

        private static void Generate()
        {
            if (EditorApplication.isCompiling || BuildPipeline.isBuildingPlayer)
            {
                return;
            }

            PackageInfo packageInfo = PackageInfo.FindForAssembly(
                typeof(SingletonAutoLoadManifestGenerator).Assembly
            );
            string packagePath = packageInfo != null ? packageInfo.resolvedPath : null;
            if (string.IsNullOrEmpty(packagePath))
            {
                return;
            }

            string outputPath = Path.Combine(packagePath, OutputRelativePath);
            Directory.CreateDirectory(Path.GetDirectoryName(outputPath));

            List<(Type Type, AutoLoadSingletonAttribute Attribute)> attributedTypes =
                CollectAttributedTypes();
            attributedTypes.Sort(
                (left, right) => string.CompareOrdinal(left.Type.FullName, right.Type.FullName)
            );

            string content = Render(attributedTypes);

            if (File.Exists(outputPath))
            {
                string existing = File.ReadAllText(outputPath, Encoding.UTF8);
                if (string.Equals(existing, content, StringComparison.Ordinal))
                {
                    return;
                }
            }

            File.WriteAllText(outputPath, content, Encoding.UTF8);
            AssetDatabase.ImportAsset(RelativeAssetPath(outputPath));
        }

        private static List<(Type, AutoLoadSingletonAttribute)> CollectAttributedTypes()
        {
            List<(Type, AutoLoadSingletonAttribute)> result = new();
            foreach (Type type in TypeCache.GetTypesWithAttribute<AutoLoadSingletonAttribute>())
            {
                if (type == null || type.IsAbstract || type.ContainsGenericParameters)
                {
                    continue;
                }

                AutoLoadSingletonAttribute attribute =
                    Attribute
                        .GetCustomAttributes(type, typeof(AutoLoadSingletonAttribute), false)
                        .FirstOrDefault() as AutoLoadSingletonAttribute;
                if (attribute == null)
                {
                    continue;
                }

                if (!IsRuntimeSingleton(type) && !IsScriptableObjectSingleton(type))
                {
                    Debug.LogWarning(
                        $"[SingletonAutoLoadManifest] Ignoring {type.FullName} because it does not derive from RuntimeSingleton<> or ScriptableObjectSingleton<>."
                    );
                    continue;
                }

                result.Add((type, attribute));
            }
            return result;
        }

        private static bool IsRuntimeSingleton(Type type)
        {
            return InheritsFromOpenGeneric(
                type,
                typeof(WallstopStudios.UnityHelpers.Utils.RuntimeSingleton<>)
            );
        }

        private static bool IsScriptableObjectSingleton(Type type)
        {
            return InheritsFromOpenGeneric(
                type,
                typeof(WallstopStudios.UnityHelpers.Utils.ScriptableObjectSingleton<>)
            );
        }

        private static bool InheritsFromOpenGeneric(Type type, Type openGeneric)
        {
            if (type == null || openGeneric == null)
            {
                return false;
            }

            Type current = type;
            while (current != null && current != typeof(object))
            {
                if (current.IsGenericType && current.GetGenericTypeDefinition() == openGeneric)
                {
                    return true;
                }
                current = current.BaseType;
            }
            return false;
        }

        private static string Render(List<(Type Type, AutoLoadSingletonAttribute Attribute)> types)
        {
            StringBuilder builder = new StringBuilder();
            builder.AppendLine(AutoGeneratedHeader);
            builder.AppendLine("using System;");
            builder.AppendLine("using UnityEngine;");
            builder.AppendLine("using WallstopStudios.UnityHelpers.Utils;");
            builder.AppendLine("using WallstopStudios.UnityHelpers.Core.Helper;");
            builder.AppendLine();
            builder.AppendLine("namespace WallstopStudios.UnityHelpers.Core.Helper");
            builder.AppendLine("{");
            builder.AppendLine("    internal static partial class SingletonAutoLoadManifest");
            builder.AppendLine("    {");
            builder.AppendLine(
                "        static partial void Populate(System.Collections.Generic.List<SingletonAutoLoadDescriptor> target)"
            );
            builder.AppendLine("        {");

            foreach ((Type type, AutoLoadSingletonAttribute attribute) in types)
            {
                string qualifiedName = $"global::{type.FullName}";
                string method = IsRuntimeSingleton(type)
                    ? "SingletonAutoLoadDescriptor.Runtime"
                    : "SingletonAutoLoadDescriptor.ScriptableObject";
                builder.AppendLine(
                    $"            target.Add({method}<{qualifiedName}>(RuntimeInitializeLoadType.{attribute.LoadType}));"
                );
            }

            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string RelativeAssetPath(string absolutePath)
        {
            absolutePath = absolutePath.Replace("\\", "/");
            int assetsIndex = absolutePath.IndexOf("/Assets/", StringComparison.OrdinalIgnoreCase);
            if (assetsIndex >= 0)
            {
                return absolutePath.Substring(assetsIndex + 1);
            }

            int packagesIndex = absolutePath.IndexOf(
                "/Packages/",
                StringComparison.OrdinalIgnoreCase
            );
            if (packagesIndex >= 0)
            {
                return absolutePath.Substring(packagesIndex + 1);
            }

            return absolutePath;
        }
    }
}
