name: Feature Request
description: Suggest a new feature or enhancement for Unity Helpers
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case / Motivation
      description: Why do you need this feature? What problem does it solve?
      placeholder: Describe your use case and motivation...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have ideas on how this could be implemented, describe them here.
      placeholder: Describe your proposed solution...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've considered...
    validations:
      required: false

  - type: dropdown
    id: unity-version
    attributes:
      label: Unity Version
      description: Which version of Unity are you using? (helps us prioritize)
      options:
        - "Unity 6.2 (6000.2) LTS"
        - "Unity 6.1 (6000.1)"
        - "Unity 6 (6000.0)"
        - "2022.3 LTS"
        - "2021.3 LTS"
        - "Other"
    validations:
      required: false

  - type: dropdown
    id: package-version
    attributes:
      label: Package Version
      description: Which version of Unity Helpers are you using?
      options:
        # <!-- AUTO-UPDATED: package-versions -->
        - "3.2.0"
        - "3.1.9"
        - "3.1.8"
        - "3.1.7"
        - "3.1.6"
        - "3.1.5"
        - "3.1.4"
        - "3.1.3"
        - "3.1.2"
        - "3.1.1"
        - "3.1.0"
        - "3.0.5"
        - "3.0.4"
        - "3.0.3"
        - "3.0.2"
        - "3.0.1"
        - "3.0.0"
        - "2.1.3"
        - "2.1.2"
        - "2.1.1"
        - "2.1.0"
        - "2.0.4"
        - "2.0.3"
        - "2.0.1"
        - "2.0.0"
        - "Other"
        # <!-- END AUTO-UPDATED: package-versions -->
    validations:
      required: false
